name: Sketch Compile

# the action is triggered at every pull request
on:
  - pull_request

jobs:
  sketch-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - "esp8266:esp822:d1_mini"

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # search the sketches in the current repo (no subfolders)
            - ./WeMosD1-RC522.ino

          platforms: |
            - name: "esp8266:esp8266"
              source-url: "https://github.com/esp8266/Arduino/releases/download/3.1.2/esp8266-3.1.2.zip"

          libraries: |
            - name: Arduino_time
            - name: Arduino_MFRC522
            - name: Arduino_ESP8266WiFi
            - name: Arduino_WiFiClientSecure
