name: Sketch Compile

# the action is triggered at every pull request
on:
  - pull_request
  - push

jobs:
  sketch-compile:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install python3, required for compilation for wemos d1
      - name: Install Python 3.7.2
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.7.2"

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp8266:esp8266:d1_mini"

          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # search the sketches in the current repo (no subfolders)
            - ./

          platforms: |
            - name: "esp8266:esp8266"
              source-url: "https://github.com/esp8266/Arduino/releases/download/3.1.2/esp8266-3.1.2.zip"

          libraries: |
            - name: time
            - name: MFRC522
